// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: chatroom.sql

package generated

import (
	"context"

	"github.com/google/uuid"
)

const addUserToChatroom = `-- name: AddUserToChatroom :exec
INSERT INTO
    chatroom_users (chatroom_id, user_id)
VALUES
    ($1, $2)
`

type AddUserToChatroomParams struct {
	ChatroomID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) AddUserToChatroom(ctx context.Context, arg AddUserToChatroomParams) error {
	_, err := q.db.Exec(ctx, addUserToChatroom, arg.ChatroomID, arg.UserID)
	return err
}

const getChannels = `-- name: GetChannels :many
SELECT
    ch.channel_id,
    ch.channel_name,
    ch.chatroom_id
FROM
    channels ch
    JOIN chatrooms c ON ch.chatroom_id = c.chatroom_id
    JOIN chatroom_users cu ON c.chatroom_id = cu.chatroom_id
WHERE
    cu.user_id = $1
`

func (q *Queries) GetChannels(ctx context.Context, userID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, getChannels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.ChannelID, &i.ChannelName, &i.ChatroomID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatrooms = `-- name: GetChatrooms :many
SELECT
    c.chatroom_id,
    c.chatroom_name,
    c.owner_id,
    c.icon_src
FROM
    chatrooms c
    JOIN chatroom_users cu ON c.chatroom_id = cu.chatroom_id
WHERE
    cu.user_id = $1
`

type GetChatroomsRow struct {
	ChatroomID   uuid.UUID
	ChatroomName string
	OwnerID      uuid.UUID
	IconSrc      string
}

func (q *Queries) GetChatrooms(ctx context.Context, userID uuid.UUID) ([]GetChatroomsRow, error) {
	rows, err := q.db.Query(ctx, getChatrooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatroomsRow
	for rows.Next() {
		var i GetChatroomsRow
		if err := rows.Scan(
			&i.ChatroomID,
			&i.ChatroomName,
			&i.OwnerID,
			&i.IconSrc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryChatroom = `-- name: GetPrimaryChatroom :one
SELECT
    chatroom_id
FROM
    chatrooms
ORDER BY
    chatroom_id LIMIT 1
`

func (q *Queries) GetPrimaryChatroom(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPrimaryChatroom)
	var chatroom_id uuid.UUID
	err := row.Scan(&chatroom_id)
	return chatroom_id, err
}

const getUsersInChatroom = `-- name: GetUsersInChatroom :many
SELECT
    u.user_id,
    u.username,
    u.icon_src,
    u.user_description,
    u.join_date,
    u.verified
FROM
    users u
    INNER JOIN chatroom_users cu ON u.user_id = cu.user_id
WHERE
    cu.chatroom_id = $1
`

func (q *Queries) GetUsersInChatroom(ctx context.Context, chatroomID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInChatroom, chatroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.IconSrc,
			&i.UserDescription,
			&i.JoinDate,
			&i.Verified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannel = `-- name: InsertChannel :exec
INSERT INTO channels (channel_name, chatroom_id)
VALUES ($1, $2)
`

type InsertChannelParams struct {
	ChannelName string
	ChatroomID  uuid.UUID
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) error {
	_, err := q.db.Exec(ctx, insertChannel, arg.ChannelName, arg.ChatroomID)
	return err
}

const insertChatroom = `-- name: InsertChatroom :one
INSERT INTO chatrooms (chatroom_name, icon_src, owner_id)
VALUES ($1, $2, $3)
RETURNING chatroom_id
`

type InsertChatroomParams struct {
	ChatroomName string
	IconSrc      string
	OwnerID      uuid.UUID
}

func (q *Queries) InsertChatroom(ctx context.Context, arg InsertChatroomParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertChatroom, arg.ChatroomName, arg.IconSrc, arg.OwnerID)
	var chatroom_id uuid.UUID
	err := row.Scan(&chatroom_id)
	return chatroom_id, err
}

const insertChatroomUser = `-- name: InsertChatroomUser :exec
INSERT INTO chatroom_users (chatroom_id, user_id)
VALUES ($1, $2)
`

type InsertChatroomUserParams struct {
	ChatroomID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) InsertChatroomUser(ctx context.Context, arg InsertChatroomUserParams) error {
	_, err := q.db.Exec(ctx, insertChatroomUser, arg.ChatroomID, arg.UserID)
	return err
}
