// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: credentials.sql

package generated

import (
	"context"

	"github.com/google/uuid"
)

const addUserToCredentials = `-- name: AddUserToCredentials :one
INSERT INTO credentials (user_id, session_token)
VALUES ($1, gen_random_uuid())
RETURNING session_token
`

func (q *Queries) AddUserToCredentials(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addUserToCredentials, userID)
	var session_token uuid.UUID
	err := row.Scan(&session_token)
	return session_token, err
}
