// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: icon.sql

package repository

import (
	"context"
)

const createIcon = `-- name: CreateIcon :exec
INSERT INTO
    icons (icon_id, link, kind)
VALUES
    ($1, $2, $3)
`

type CreateIconParams struct {
	IconID int32
	Link   string
	Kind   string
}

func (q *Queries) CreateIcon(ctx context.Context, arg CreateIconParams) error {
	_, err := q.db.Exec(ctx, createIcon, arg.IconID, arg.Link, arg.Kind)
	return err
}
