// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: icon.sql

package generated

import (
	"context"
)

const getRandomDefaultIcon = `-- name: GetRandomDefaultIcon :one
SELECT icon_id, kind, link, is_default
FROM icons
WHERE is_default = true
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomDefaultIcon(ctx context.Context) (Icon, error) {
	row := q.db.QueryRow(ctx, getRandomDefaultIcon)
	var i Icon
	err := row.Scan(
		&i.IconID,
		&i.Kind,
		&i.Link,
		&i.IsDefault,
	)
	return i, err
}
