// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Icon struct {
	IconID int32
	Link   string
	Kind   string
}

type User struct {
	UserID   int32
	Username string
	IconID   int32
	JoinDate pgtype.Date
	Verified bool
}
