// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package generated

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ChannelID   uuid.UUID
	ChannelName string
	ChatroomID  uuid.UUID
}

type Chatroom struct {
	ChatroomID   uuid.UUID
	ChatroomName string
	IconSrc      string
	OwnerID      uuid.UUID
}

type ChatroomUser struct {
	ChatroomID uuid.UUID
	UserID     uuid.UUID
}

type Credential struct {
	UserID       uuid.UUID
	HashPassword pgtype.Text
	SessionToken uuid.UUID
}

type User struct {
	UserID          uuid.UUID
	Username        string
	IconSrc         string
	UserDescription pgtype.Text
	JoinDate        pgtype.Date
	Verified        bool
}
